addons:
  postgresql: "9.4"

services:
  - postgresql
  - redis-server

matrix:
    include:
        - python: 3.4
        - python: 3.5

cache:
  directories:
    - wheelhouse

# https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - python --version
  - which pip
  - bash websauna/tests/create_wheelhouse.bash
  - pip install -e ".[test]"
  - py.test --splinter-webdriver=firefox --splinter-make-screenshot-on-failure=true --ini=travis.ini --timeout=200 --durations=10 --cov-report xml --cov websauna --cov-config .coveragerc $PROJECT_NAME


after_script:
  - codecov --token=$CODECOV_TOKEN
  - pip freeze

