language: python
dist: trusty

services:
  - postgresql
  - redis-server

matrix:
    fast_finish: true
    include:
        - python: 3.6
          env:
          - PYTHON_VERSION=python3.6
          - TOXENV=style

# http://stackoverflow.com/a/19460794/315168
cache:
  directories:
    # /home/travis/.cache/pip/wheels is the normal pip cache folder
    - $HOME/.cache/pip

install:
  - travis_retry pip install tox

before_script:
  - pip install -U pip

script:
  - tox -e $TOXENV
