language: python

addons:
  postgresql: "9.4"

services:
  - postgresql
  - redis-server

matrix:
    include:
        - python: 3.4
        - python: 3.5

# http://stackoverflow.com/a/19460794/315168
cache:
  directories:
    - $HOME/.cache/pip
    - wheelhouse

# https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - psql -c 'create database websauna_test;' -U postgres
  - pip install -U pip

script:
  - if [ ! -d wheelhouse ] ; then bash websauna/tests/create_wheelhouse.bash ; fi
  - pip install -q wheelhouse/*
  - pip install -q -e ".[test]"
  - py.test --splinter-webdriver=firefox --splinter-make-screenshot-on-failure=true --ini=travis.ini --timeout=200 --durations=10 --cov-report xml --cov websauna --cov-config .coveragerc websauna


after_script:
  - codecov --token=$CODECOV_TOKEN
  - pip freeze

